### ISSUE TITLE
Exception while running hub-detect

### ISSUE THREAD

**Issue by omerlh** [blackducksoftware/hub-detect#22] opened 2017-06-19 13:57 UTC
I tried to run the hub-detect, and it failed with a very unclear error. I know this is beta, but I was asked by the support to try it out. This is the configuration file:
```yml
detect.hub.url=***
detect.hub.timeout=120
detect.hub.username=***
detect.hub.password=****

detect.hub.auto.import.cert=

detect.hub.proxy.host=
detect.hub.proxy.port=
detect.hub.proxy.username=
detect.hub.proxy.password=

detect.source.paths=ios
detect.output.path=
detect.search.depth=
detect.cleanup.bdio.files=
detect.cleanup.bom.tool.files=
detect.bom.aggregate=
detect.bom.tool.type.override=
detect.search.depth=

detect.project.name=test
detect.project.version.name=1

detect.gradle.inspector.version=
detect.gradle.path=
detect.gradle.build.command=
detect.gradle.excluded.configurations=
detect.gradle.included.configurations=
detect.gradle.excluded.projects=
detect.gradle.included.projects=

detect.pip.project.name=
detect.pip.create.virtual.env=
detect.pip.pip3=
detect.pip.requirements.path=
detect.pip.virtualEnv.path=
detect.pip.path=
detect.python.path=

detect.maven.scope=
detect.maven.aggregate=
detect.maven.path=

detect.nuget.inspector.name=
detect.nuget.inspector.version=
detect.nuget.aggregate=
detect.nuget.ignore.failure=
detect.nuget.excluded.modules=
detect.nuget.path=

detect.godep.path=
detect.go.aggregate=

detect.docker.inspector.path=
detect.docker.inspector.version=
detect.docker.install.path=
detect.docker.sandbox.path=
detect.docker.tar=
detect.docker.image=
detect.docker.path=
detect.bash.path=

logging.level.com.blackducksoftware.integration=INFO

```
I am running it by using `bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh)  --spring.config.location=application.properties`. And this is the error:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    41  100    41    0     0    150      0 --:--:-- --:--:-- --:--:--   150
will look for release: hub-detect-0.0.4.jar
You have already downloaded the latest file, so the local file will be used.
running detect: /tmp/hub-detect-0.0.4.jar --spring.config.location=application.properties

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.2.RELEASE)

2017-06-19 16:53:57.732  INFO 39477 --- [           main] c.b.integration.hub.detect.Application   : Starting Application on OmerL-Mac with PID 39477 (/private/tmp/hub-detect-0.0.4.jar started by omerl in /Users/omerl/dev/soluto-home-app)
2017-06-19 16:53:57.739  INFO 39477 --- [           main] c.b.integration.hub.detect.Application   : No active profile set, falling back to default profiles: default
2017-06-19 16:53:57.908  INFO 39477 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@725bef66: startup date [Mon Jun 19 16:53:57 IDT 2017]; root of context hierarchy
2017-06-19 16:53:59.708  WARN 39477 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'application': Unsatisfied dependency expressed through field 'bomToolManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bomToolManager': Unsatisfied dependency expressed through field 'detectProperties'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'detectProperties': Unsatisfied dependency expressed through field 'inspectorIgnoreFailure'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []
2017-06-19 16:53:59.721  INFO 39477 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-06-19 16:53:59.758 ERROR 39477 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'application': Unsatisfied dependency expressed through field 'bomToolManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bomToolManager': Unsatisfied dependency expressed through field 'detectProperties'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'detectProperties': Unsatisfied dependency expressed through field 'inspectorIgnoreFailure'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) ~[spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) ~[spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder$run$0.call(Unknown Source) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-all-2.4.11.jar!/:2.4.11]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-all-2.4.11.jar!/:2.4.11]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-all-2.4.11.jar!/:2.4.11]
	at com.blackducksoftware.integration.hub.detect.Application.main(Application.groovy:55) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [hub-detect-0.0.4.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [hub-detect-0.0.4.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [hub-detect-0.0.4.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [hub-detect-0.0.4.jar:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bomToolManager': Unsatisfied dependency expressed through field 'detectProperties'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'detectProperties': Unsatisfied dependency expressed through field 'inspectorIgnoreFailure'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	... 29 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'detectProperties': Unsatisfied dependency expressed through field 'inspectorIgnoreFailure'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	... 42 common frames omitted
Caused by: org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []
	at org.springframework.beans.TypeConverterSupport.doConvert(TypeConverterSupport.java:77) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:54) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1092) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	... 55 common frames omitted
Caused by: java.lang.IllegalArgumentException: Invalid boolean value []
	at org.springframework.beans.propertyeditors.CustomBooleanEditor.setAsText(CustomBooleanEditor.java:123) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:468) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:441) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:199) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:125) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.TypeConverterSupport.doConvert(TypeConverterSupport.java:61) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	... 59 common frames omitted
```

**Comment by utsavsanghani** [comment] 2017-06-19 14:03
@ekerwin can you validate this?

**Comment by jrichardBD** [comment] 2017-06-19 15:29
It seems version 0.0.4 must have values for the fields that are Boolean.  This wont be true in the future. The configuration file that is supplied with 0.0.4 does contain the defaults, you should keep the defaults or change them to what you want them to be. Deleting the entirely is not an option. 

Here is the default configuration file :

`
detect.hub.url=
detect.hub.timeout=120
detect.hub.username=
detect.hub.password=

detect.hub.auto.import.cert=

detect.hub.proxy.host=
detect.hub.proxy.port=
detect.hub.proxy.username=
detect.hub.proxy.password=

detect.source.paths=
detect.output.path=
detect.search.depth=10
detect.cleanup.bdio.files=true
detect.bom.aggregate=true
detect.bom.tool.type.override=
detect.search.depth=

detect.project.name=
detect.project.version=

detect.gradle.inspector.version=0.0.6
detect.gradle.path=
detect.gradle.build.command=dependencies
detect.gradle.excluded.configurations=
detect.gradle.included.configurations=
detect.gradle.excluded.projects=
detect.gradle.included.projects=

detect.pip.create.virtual.env=true
detect.pip.pip3=false
detect.pip.requirements.path=
detect.pip.virtualEnv.path=
detect.pip.path=
detect.python.path=

detect.maven.scope=
detect.maven.aggregate=true
detect.maven.path=

detect.nuget.inspector.name=IntegrationNugetInspector
detect.nuget.inspector.version=0.0.3-alpha
detect.nuget.aggregate=false
detect.nuget.ignore.failure=false
detect.nuget.excluded.modules=
detect.nuget.path=

detect.godep.path=
detect.go.aggregate=true

detect.docker.inspector.version=0.0.3-SNAPSHOT
detect.docker.install.path=
detect.docker.sandbox.path=
detect.docker.tar=
detect.docker.image=

logging.level.com.blackducksoftware.integration=INFO
`

**Comment by akamen** [comment] 2017-06-19 15:47
@omerlh thanks for filing the issue. Closing this down as it is not a bug, we did not anticipate that our default values would be purged - but as @jrichardBD  mentioned this will be mitigated in a future release.

**Closed by akamen** 2017-06-19 15:47 UTC

**Comment by omerlh** [comment] 2017-06-21 03:58
Hey, I am glad to hear this is the problem! 
I took the configuration file from the [code](https://github.com/blackducksoftware/hub-detect/blob/master/src/main/resources/application.properties), as it was not clear from the [wiki](https://github.com/blackducksoftware/hub-detect/wiki) page from where I should take it. If you'd like, I can help and update it.
